/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DAO.NhanVienDAO;
import Entity.NhanVien;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.regex.Matcher;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QuanLyNhanVien extends javax.swing.JFrame {

    private NhanVienDAO nhanVienDao = new NhanVienDAO();

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() {
        initComponents();
        loadTableNhanVien();
        ButtonGroup genderGroup = new ButtonGroup();
        genderGroup.add(jRadioButton1); // Thêm jRadioButton1 (Nam)
        genderGroup.add(jRadioButton2); // Thêm jRadioButton2 (Nữ)
    }

    private void loadTableNhanVien() {
        NhanVienDAO dao = new NhanVienDAO();
        List<NhanVien> list = dao.getAllNhanVien();

        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ

        for (NhanVien nv : list) {
            model.addRow(new Object[]{
                nv.getMaNV(),
                nv.getTenNV(),
                nv.getNgaySinh(),
                nv.getGioiTinh(),
                nv.getDiaChi(),
                nv.getSoDienThoai(),
                nv.getVaiTro(),
                nv.getMaTK(),});
        }
    }

    public class MainForm extends javax.swing.JFrame {

        public MainForm() {
            initComponents();
            loadTableNhanVien();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jSeparator1 = new javax.swing.JSeparator();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField11 = new javax.swing.JTextField();
        jDialog1 = new javax.swing.JDialog();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil2 = new org.jdatepicker.util.JDatePickerUtil();
        jDatePickerUtil3 = new org.jdatepicker.util.JDatePickerUtil();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        anh_nen = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btlExit = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jScrollPane1.setViewportView(jEditorPane1);

        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Nhân Viên\n");
        setBackground(new java.awt.Color(255, 255, 204));
        setIconImages(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thông Tin Nhân Viên");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã Nhân Viên :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 160, 22));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tên Nhân Viên :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Giới Tính :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 83, 24));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ngày Sinh :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 83, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Địa Chỉ :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 83, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("SĐT :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 83, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Mã Tài Khoản :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 108, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Vai Trò :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 83, -1));

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton1.setText("Nam ");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton2.setText("Nữ");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 160, 22));

        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 160, 22));

        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 160, 22));

        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 160, 22));

        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 160, 22));

        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 160, 22));

        anh_nen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/anh.png"))); // NOI18N
        jPanel1.add(anh_nen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 290));

        jPanel3.setBackground(new java.awt.Color(153, 51, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(848, 102));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Danh Sách Nhân Viên ");

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên ", "Tên Nhân Viên ", "Ngày Sinh", "Giới Tính", "Địa Chỉ", "SĐT", "Vai Trò ", "Mã Tài Khoản "
            }
        ));
        jScrollPane2.setViewportView(tblNhanVien);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        jButton5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/tools (1).png"))); // NOI18N
        jButton5.setText("Sửa");
        jButton5.setBorder(new javax.swing.border.MatteBorder(null));
        jButton5.setIconTextGap(8);
        jButton5.setMaximumSize(new java.awt.Dimension(539, 514));
        jButton5.setMinimumSize(new java.awt.Dimension(16, 16));
        jButton5.setPreferredSize(new java.awt.Dimension(539, 514));
        jButton5.setBorder(new javax.swing.border.MatteBorder(null));
        jButton5.setMaximumSize(new java.awt.Dimension(150, 40));
        jButton5.setMinimumSize(new java.awt.Dimension(150, 40));
        jButton5.setPreferredSize(new java.awt.Dimension(150, 40));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_Click(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/add (2).png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.setIconTextGap(10);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_Click(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/trash-bin (1) (2).png"))); // NOI18N
        jButton6.setText("Xóa ");
        jButton6.setBorder(new javax.swing.border.MatteBorder(null));
        jButton6.setIconTextGap(10);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_Click(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/magnifier (1).png"))); // NOI18N
        jButton4.setText("Tìm KIếm");
        jButton4.setBorder(new javax.swing.border.MatteBorder(null));
        jButton4.setIconTextGap(10);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiem_Click(evt);
            }
        });

        btlExit.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btlExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/logout (2).png"))); // NOI18N
        btlExit.setText("Exit");
        btlExit.setBorder(new javax.swing.border.MatteBorder(null));
        btlExit.setIconTextGap(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btlExit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btlExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

//    nut them
    private void btnThem_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_Click
        // TODO add your handling code here:  
        try {
            DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();

            String maNV = jTextField1.getText();
            String tenNV = jTextField2.getText();
            String ngaySinh = jTextField3.getText().trim();
            String gioiTinh = jRadioButton1.isSelected() ? "Nam" : "Nữ";
            String diaChi = jTextField7.getText().trim();
            String sdt = jTextField12.getText().trim();
            String vaiTro = jTextField13.getText();
            String maTK = jTextField14.getText();

            if (maNV.isEmpty() || tenNV.isEmpty() || ngaySinh.isEmpty() || diaChi.isEmpty()
                    || sdt.isEmpty() || vaiTro.isEmpty() || maTK.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
                return;
            }

            // Validate input
            if (maNV.isEmpty() || tenNV.isEmpty() || ngaySinh.isEmpty() || diaChi.isEmpty()
                    || sdt.isEmpty() || vaiTro.isEmpty() || maTK.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
                return;
            }

            if (!maNV.matches("^NV\\d+$")) {
                JOptionPane.showMessageDialog(this, "Mã nhân viên phải có dạng NV kèm theo số, ví dụ: NV001");
                return;
            }

            // Validate soDienThoai (max 10 digits, numeric only)
            if (!(sdt.length() == 10) || !sdt.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ. Phải là số và tối đa 10 chữ số.");
                return;
            }

            // Validate ngaySinh (must be a valid date in yyyy-MM-dd format)
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            try {
                LocalDate ngaySinhLocal = LocalDate.parse(ngaySinh, formatter);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ. Vui lòng nhập định dạng dd/MM/yyyy (ví dụ: 25/12/2023).");
                return;
            }
            NhanVien nhanVienNew = new NhanVien(maNV, tenNV, ngaySinh, gioiTinh, diaChi, sdt, vaiTro, maTK);

            NhanVien x = nhanVienDao.getNhanVienById(maNV);
            if (x != null) {

                // Xóa dữ liệu ô nhập sau khi thêm
                jTextField1.setText(maNV);
                jTextField2.setText(tenNV);
                jTextField3.setText(ngaySinh);
                jTextField7.setText(diaChi);
                jTextField12.setText(sdt);
                jTextField13.setText(vaiTro);
                jTextField14.setText(maTK);
                jRadioButton1.setSelected(true);
                JOptionPane.showMessageDialog(this, "Mã nhân viên không được trùng");
                return;
            }// reset về Nam
            if (!maTK.equals("TK001") && !maTK.equals("TK002") && !maTK.equals("TK003")) {
                JOptionPane.showMessageDialog(this, "Mã tài khoản phải hợp lệ");
                return;
            }
            model.addRow(new Object[]{maNV, tenNV, ngaySinh, gioiTinh, diaChi, sdt, vaiTro, maTK});

            boolean checkUpdate = nhanVienDao.createNhanVienById(nhanVienNew);
            if (checkUpdate) {
                System.out.println("Thêm thành công");
            } else {
                System.out.println("Đéo thành công");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm dữ liệu: " + e.getMessage());
        }
    }//GEN-LAST:event_btnThem_Click

    private void btnTimKiem_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiem_Click
        // TODO add your handling code here:
        try {
            // Hiển thị hộp thoại để nhập mã nhân viên
            String maNV = JOptionPane.showInputDialog(this, "Nhập mã nhân viên để tìm kiếm:", "Tìm Kiếm", JOptionPane.QUESTION_MESSAGE);

            // Kiểm tra xem người dùng có nhập mã hay không
            if (maNV == null || maNV.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên.");
                return;
            }

            // Lấy mô hình bảng
            DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
            int rowCount = model.getRowCount();
            int foundRow = -1;

            // Tìm kiếm dòng có mã nhân viên phù hợp
            for (int i = 0; i < rowCount; i++) {
                String currentMaNV = (String) model.getValueAt(i, 0); // Cột 0 là MaNhanVien
                if (currentMaNV != null && currentMaNV.equalsIgnoreCase(maNV.trim())) {
                    foundRow = i;
                    break;
                }
            }

            // Nếu không tìm thấy, hiển thị thông báo
            if (foundRow == -1) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên có mã " + maNV + ".");
                return;
            }

            // Chọn và cuộn đến dòng tìm thấy
            tblNhanVien.setRowSelectionInterval(foundRow, foundRow);
            tblNhanVien.scrollRectToVisible(tblNhanVien.getCellRect(foundRow, 0, true));

            JOptionPane.showMessageDialog(this, "Đã tìm thấy nhân viên có mã " + maNV + "!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tìm kiếm: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTimKiem_Click

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btnXoa_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa_Click
        // TODO add your handling code here:
        try {
            // Lấy dòng được chọn trong bảng
            int selectedRow = tblNhanVien.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa.");
                return;
            }

            // Xác nhận trước khi xóa
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Bạn có chắc chắn muốn xóa nhân viên này?",
                    "Xác nhận xóa",
                    JOptionPane.YES_NO_OPTION);

            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }

            nhanVienDao.deleteNhanVienById((String) tblNhanVien.getValueAt(selectedRow, 0));

            // Lấy mô hình bảng và xóa dòng được chọn
            DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
            model.removeRow(selectedRow);

            // Thông báo xóa thành công
            JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa: " + e.getMessage());
        }
    }//GEN-LAST:event_btnXoa_Click

    private void btnSua_Click(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua_Click
        // TODO add your handling code here:
        try {
        // Lấy dòng được chọn
        int selectedRow = tblNhanVien.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để sửa.");
            return;
        }

        // Lấy thông tin hiện tại từ bảng
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        String maNV = (String) model.getValueAt(selectedRow, 0); // Mã nhân viên không thay đổi
        String tenNV = (String) model.getValueAt(selectedRow, 1);
        String ngaySinh = (String) model.getValueAt(selectedRow, 2);
        String gioiTinh = (String) model.getValueAt(selectedRow, 3);
        String diaChi = (String) model.getValueAt(selectedRow, 4);
        String sdt = (String) model.getValueAt(selectedRow, 5);
        String vaiTro = (String) model.getValueAt(selectedRow, 6);
        String maTK = (String) model.getValueAt(selectedRow, 7);

        // Lấy giá trị từ các ô nhập liệu, nếu trống thì giữ nguyên giá trị cũ
        String newMaNV = jTextField1.getText().trim();
        String newTenNV = jTextField2.getText().trim();
        String newNgaySinh = jTextField3.getText().trim();
        String newGioiTinh = jRadioButton1.isSelected() ? "Nam" : "Nữ";
        String newDiaChi = jTextField7.getText().trim();
        String newSdt = jTextField12.getText().trim();
        String newVaiTro = jTextField13.getText().trim();
        String newMaTK = jTextField14.getText().trim();

        // Kiểm tra và giữ nguyên giá trị cũ nếu ô trống
        if (!newTenNV.isEmpty()) tenNV = newTenNV;
        if (!newNgaySinh.isEmpty()) ngaySinh = newNgaySinh;
        if (!newDiaChi.isEmpty()) diaChi = newDiaChi;
        if (!newSdt.isEmpty()) sdt = newSdt;
        if (!newVaiTro.isEmpty()) vaiTro = newVaiTro;
        if (!newMaTK.isEmpty()) maTK = newMaTK;
        gioiTinh = newGioiTinh; // Giới tính luôn được cập nhật từ radio button


        // Kiểm tra các trường bắt buộc không được để trống
        if (tenNV.isEmpty() || ngaySinh.isEmpty() || diaChi.isEmpty() || sdt.isEmpty() || vaiTro.isEmpty() || maTK.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Các trường không được để trống hoàn toàn.");
            return;
        }

        // Validate SĐT
        if (sdt.length() > 10 || !sdt.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không hợp lệ. Phải là số và tối đa 10 chữ số.");
            return;
        }

        // Validate Ngày Sinh
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        Date ngaySinhDate;
        try {
            LocalDate ngaySinhLocal = LocalDate.parse(ngaySinh, formatter);
            ngaySinhDate = java.sql.Date.valueOf(ngaySinhLocal);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ngày sinh không hợp lệ. Vui lòng nhập định dạng dd/MM/yyyy (ví dụ: 25/12/2023).");
            return;
        }

        // Tạo đối tượng NhanVien với dữ liệu đã cập nhật
        NhanVien nv = new NhanVien(maNV, tenNV, ngaySinhDate.toString(), gioiTinh, diaChi, sdt, vaiTro, maTK);

        // Cập nhật cơ sở dữ liệu
        boolean updateCheck = nhanVienDao.updateNhanVien(nv);

        // Cập nhật bảng nếu cơ sở dữ liệu cập nhật thành công
        if (updateCheck) {
            model.setValueAt(maNV, selectedRow, 0);
            model.setValueAt(tenNV, selectedRow, 1);
            model.setValueAt(ngaySinh, selectedRow, 2);
            model.setValueAt(gioiTinh, selectedRow, 3);
            model.setValueAt(diaChi, selectedRow, 4);
            model.setValueAt(sdt, selectedRow, 5);
            model.setValueAt(vaiTro, selectedRow, 6);
            model.setValueAt(maTK, selectedRow, 7);

            // Xóa các ô nhập liệu sau khi sửa
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField7.setText("");
            jTextField12.setText("");
            jTextField13.setText("");
            jTextField14.setText("");
            jRadioButton1.setSelected(true);

            JOptionPane.showMessageDialog(this, "Cập nhật thông tin nhân viên thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại. Vui lòng kiểm tra lại dữ liệu.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi sửa: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnSua_Click

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anh_nen;
    private javax.swing.JButton btlExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil2;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTable tblNhanVien;
    // End of variables declaration//GEN-END:variables
}
